### ISSUE TITLE
chunkhash of produced assets changes even if source stays the same

### ISSUE THREAD

**Issue by sheerun** [BohdanTkachenko/webpack-split-by-path#7] opened 2015-11-27 20:49 UTC
Hey,

I tried to use your plugin, but the chunkhash of my vendor chunk changes even if I don't modify any of my vendor dependencies.. Here is my configuration:

```
    new SplitByPathPlugin([
      {
        name: 'vendor',
        path: path.join(__dirname, 'node_modules')
      }
    ])
```

Any tips?

**Comment by sheerun** [comment] 2015-11-27 20:49
I only changed application code.

**Comment by sheerun** [comment] 2015-11-27 23:00
The vendor file differs only in following:

```
79c79
< /******/                      script.src = __webpack_require__.p + "" + ({"0":"index"}[chunkId]||chunkId) + "-" + {"0":"e87843f64ed5fbf75cab"}[chunkId] + ".js";
---
> /******/                      script.src = __webpack_require__.p + "" + ({"0":"index"}[chunkId]||chunkId) + "-" + {"0":"556dee5231cea6b6d18a"}[chunkId] + ".js";
25564c25564
< //# sourceMappingURL=vendor-e2ddf7a8873cca94ab3b.js.map
\ No newline at end of file
---
> //# sourceMappingURL=vendor-ef861294c72026118f27.js.map
\ No newline at end of file
```

**Comment by BohdanTkachenko** [comment] 2015-11-28 11:53
Can you please provide sample project where this can be reproduced? I'll try to debug it

**Comment by sheerun** [comment] 2015-11-28 12:16
It' the default one you provided in the readme:
https://github.com/sheerun/webpack-split

Please change v2 to v3 in index.js, and notice that vendor contents and chunkhash changes upon rebuild

**Comment by sheerun** [comment] 2015-11-28 23:03
The comment in vendor bundle says:

```
/******/    // This file contains only the entry chunk.
/******/    // The chunk loading function for additional chunks
```

Shouldn't it be the other way around? The index chunk should be entry chunk and load vendor one..

**Comment by e-cloud** [comment] 2016-05-18 15:18
+1, the hash of seldom changed vendor.js should not change every compilation

**Comment by mosanger** [comment] 2016-05-19 13:08
+1

**Comment by s-panferov** [comment] 2016-06-15 14:47
Related thread: https://github.com/webpack/webpack/issues/1315

The main idea there is to extract `manifest` chunk that changes every time.

**Comment by spiffytech** [comment] 2016-06-17 14:28
:+1:

**Comment by BohdanTkachenko** [comment] 2016-06-17 21:09
Sorry, I don't have much free time now, so I can't quickly fix this issue, but I will be able to accept PR if someone will make one.

**Comment by e-cloud** [comment] 2016-06-29 12:45
so should we separate the manifest module to a standalone chunk as built-in behavior of this plugin or just an option?

**Comment by BohdanTkachenko** [comment] 2016-07-06 20:43
@e-cloud did a pull request that seems to be fixing this issue. Closing this issue for now. Please re-open it if there still any problems

**Closed as completed by BohdanTkachenko** 2016-07-06 20:43 UTC
